server:
  port: 9100
#logging:
#  level:
#    root: debug
logging:
  level:
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: trace
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:9090"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
      routes:
        - id: core-service
          uri: http://localhost:9099/
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
            - PrefixPath=/
            - JwtAuthFilter
        - id: cart-service
          uri: http://localhost:9091
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
            - PrefixPath=/
            - JwtAuthFilter
        - id: users-service
          uri: http://localhost:9095
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1
            - PrefixPath=/
            - JwtAuthFilter
        - id: order-service
          uri: http://localhost:9094
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
            - PrefixPath=/
            - JwtAuthFilter
        - id: auth-user-service
          uri: http://localhost:9095
          predicates:
            - Path=/auth/**
          filters:
            - JwtAuthFilter
        - id: registration-user-service
          uri: http://localhost:9095
          predicates:
            - Path=/registration/**
          filters:
            - JwtAuthFilter
