server:
  port: 9094
#  servlet:
#    context-path: /market-user
#logging:
#  level:
#    root: debug
spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://localhost:9500/realms/market/protocol/openid-connect/token/introspect
          client-id: quotes-client
          client-secret: G4MuSHTHXP14ryg5VQWDB2qyKjhejoUl
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/market
    username: w0id
    password: 2311
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
#    hibernate:
#      ddl-auto: create
integrations:
  customer-service:
    url: http://localhost:9095/
    connect-timeout: 5000
    read-timeout: 10000
    write-timeout: 5000
  core-service:
    url: http://localhost:9099/
    connect-timeout: 5000
    read-timeout: 10000
    write-timeout: 5000
  cart-service:
    url: http://localhost:9091/
    connect-timeout: 5000
    read-timeout: 10000
    write-timeout: 5000